### ISSUE TITLE
2016年度の成果

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#1]
@AriYu 
今年の進捗はこのリポジトリを基点にするという認識で正しいですか？

**Comment by AriYu** [comment]
@MoriKen254 
3号機のコアな部分なプログラムはこのリポジトリで管理します。
一方で、例えばつくばチャレンジ2016でしか使わないようなプログラム等に関しては別途当該リポジトリを作成し、そこで管理していきたいと考えています。
また、例えばウェイポイントを管理するようなプログラムや人物検出を行うプログラムなど毎年改良を重ねていく必要があるようなプログラムに関しても別にリポジトリを作成し、そこにコミットしていく感じにしたいと考えています。
つくばチャレンジ2016のリポジトリにはそれらのリポジトリ（やこのリポジトリ）へのリンクとして管理するようにする（例えば`git submodule`や`git subtree`を使う）か`dependencies`ファイルを管理してやるか、どちらかを考えています。

**Comment by MoriKen254** [comment]
@AriYu 
ありがとうございます．了解しました．「コアな部分」がどこまで指すかがミソですね．
例えば，下記のプログラムはどうなりますか？
- ステアロボット用のコントローラ
- gazebo用のRobotHWSim
- ステアロボット用のリカバリ行動

私の勝手な所感ですが，コントローラとHWSimはコアかなと．
一方リカバリは出来次第ではコアになるし，メンテが必要になるかもしれない？という感触です．

**Comment by AriYu** [comment]
@MoriKen254 
そうですね。
リカバリの動作が汎用的に実装可能であれば、そちらのほうがいいですね。
バックしてリカバリというのは結構、需要があるかもしれません。
ただ、あるプログラムだけど別リポジトリに切り出す（コミット履歴を残したまま）のは難しくないので、とりあえず、このリポジトリにコミットしてもらって、あとで判断する感じでもいいと思います。

**Comment by MoriKen254** [comment]
了解しました．とりあえずこのリポジトリにコミットするようにします．
回答ありがとうございます．
