### ISSUE TITLE
Recovery の挙動について

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#10]
RotateRecoveryに代わるRecovery行動のプラグインを作っています。今構想中の案を共有します。
要望、改善、新しいアイディア、あればよろしくお願いします。

![image](https://cloud.githubusercontent.com/assets/12078261/19338714/bc00cff0-9159-11e6-9cc2-d2f83f0f2e1b.jpg)

①: スタックした。

②: 一旦後退する。

③: 前進、右旋回、左旋回の三方向に進んだ場合それぞれについて、ローカルコストを参照しながら障害物に衝突するまでシミュレーションを行う。
障害物までの距離が最も長い方向を進路クリア方向とする。

④: ③で指定した方向に向かって舵をとって前進し、進路をクリアする。

⑤: もし全方向で殆ど同じ位置に障害物がある場合、①に戻って後退から再開。複数回連続失敗したらリターン。ローカルプランナーDWAに望みを託す。

②の後退距離または時間、③の旋回角度、④の前進距離または時間、⑤のリトライ回数はyamlで指定できるようにする。

よろしくお願いします。

**Comment by AriYu** [comment]
@MoriKen254 
良いと思います。
お忙しいとは思いますが、よろしくお願いします。

**Comment by MoriKen254** [comment]
リカバリの挙動サンプルです．とりあえず雰囲気が伝わればと．gazeboのナビ環境が揃っているロボットで検証しています．パラメータの調整は必要でしょうが，ステアでも大丈夫のはずです．
↓
https://youtu.be/j6GID9XuiiU
- 12秒あたりでスタック
- 17秒あたりでリカバリ開始

3号機のgazeboナビ環境はまだ構築できていないので，その辺りを整備してぼちぼち調整してみます．

**Comment by AriYu** [comment]
@MoriKen254 
すごいですね :clap: 
実機でもできるだけ早く試してみたいと思います。
要望なんですが当該リカバリ動作に入ったら何らかの出力（printf的な）があれば嬉しいです。

**Comment by AriYu** [comment]
@MoriKen254 
実験で、リカバリが起動して動くことは確認しました。
いろいろパラメータを変えてみて調整してみたいと思います。
ただ、問題としていつリカバリに切り替わるのかが分かっていません。
いつまでもローカルプランナーがギブアップしない場合もあればすぐにギブアップする場合もあるのでよく分かりません。

**Comment by MoriKen254** [comment]
@Ariyu

> いつリカバリに切り替わるのかが分かっていません。

当方の見解を回答します。

[indigo版move_baseのソースコード](https://github.com/ros-planning/navigation/blob/indigo-devel/move_base/src/move_base.cpp)を読むと、下記の通りと推察されます。

### 結論

デフォルトでは、下記の条件のみが有効となっているようです。
- `controller_patience`秒、停止状態が継続した場合にリカバリに移行する。

デフォルトで無効になっている条件は、下記の通りです。
- `oscillation_timeout`秒、振動行動が継続した場合にリカバリに移行する。
- `max_planning_retries`回、ローカルプランニング試行しても経路が得られなかった場合に、リカバリに移行する。
  - この設定はwikiには載っていない…。

パラメータの仕様は[move_baseのWikiページ](http://wiki.ros.org/move_base)も参照下さい。
plannerのyamlファイルで、該当パラメータを設定してみて、挙動を確認してみると良いと思います。

### 現象に対する見解

> いつまでもローカルプランナーがギブアップしない場合もあればすぐにギブアップする場合もあるのでよく分かりません。

については、環境に依存して`controller_patience`秒以内にローカルプランが得られる場合と、得られない場合があるために発生するものと推測します。もっと早く諦めて欲しい場合は、小さい値を設定すれば良さげです。

### その他

move_base が `ROS_DEBUG_NAMED` で詳しい条件分岐まで吐いくれているっぽいので、表示してみると良いかも知れません。

以下、詳細。

## 設定パラメータの仕様＋ソースコード解析

リカバリ遷移条件を規定するパラメータは3つあり、それぞれについて説明します。

### 前提: リカバリ状態に遷移する条件
- state_が"CLEARING"になるとリカバリ状態に遷移する模様です。
- 以降、この状態遷移が起こる分岐を見ていきます。

986行目

``` cpp
      //we'll try to clear out space with any user-provided recovery behaviors
      case CLEARING:
        ROS_DEBUG_NAMED("move_base","In clearing/recovery state");
        //we'll invoke whatever recovery behavior we're currently on if they're enabled
        if(recovery_behavior_enabled_ && recovery_index_ < recovery_behaviors_.size()){
          ROS_DEBUG_NAMED("move_base_recovery","Executing behavior %u of %zu", recovery_index_, recovery_behaviors_.size());
          recovery_behaviors_[recovery_index_]->runBehavior(); // ←これがリカバリ行動メソッド！
```

### 1. `controller_patience`秒、停止状態が継続した場合にリカバリに移行する。
- デフォルトは15秒。

74行目

``` cpp
    private_nh.param("controller_patience", controller_patience_, 15.0);
```

958行目

``` cpp
          ROS_DEBUG_NAMED("move_base", "The local planner could not find a valid plan.");
          ros::Time attempt_end = last_valid_control_ + ros::Duration(controller_patience_);

          //check if we've tried to find a valid control for longer than our time limit
          if(ros::Time::now() > attempt_end){
            //we'll move into our obstacle clearing mode
            publishZeroVelocity();
            state_ = CLEARING;  // state_が"CLEARING"になるとリカバリ状態に遷移する模様
            recovery_trigger_ = CONTROLLING_R;
          }
```

### 2. `oscillation_timeout`秒、振動行動が継続した場合にリカバリに移行する。
- デフォルト0。これだと振動してても一生リカバリに移らない。

77行目

``` cpp
    private_nh.param("oscillation_timeout", oscillation_timeout_, 0.0);
```

936行目

``` cpp
        //check for an oscillation condition
        if(oscillation_timeout_ > 0.0 &&
            last_oscillation_reset_ + ros::Duration(oscillation_timeout_) < ros::Time::now())
        {
          publishZeroVelocity();
          state_ = CLEARING;
          recovery_trigger_ = OSCILLATION_R;
        }
```

### 3. `max_planning_retries`回、ローカルプランニング試行しても経路が得られなかった場合に、リカバリに移行する。
- デフォルトだと-1。これだとリカバリ状態への遷移はプランニング回数に依存しない。
- ROS Wikiには記載されていない…。試してみる価値はある。

75行目

``` cpp
    private_nh.param("max_planning_retries", max_planning_retries_, -1);  // disabled by default
```

655行目

``` cpp
        ROS_DEBUG_NAMED("move_base_plan_thread","No Plan...");
        ros::Time attempt_end = last_valid_plan_ + ros::Duration(planner_patience_);

        //check if we've tried to make a plan for over our time limit or our maximum number of retries
        //issue #496: we stop planning when one of the conditions is true, but if max_planning_retries_
        //is negative (the default), it is just ignored and we have the same behavior as ever
        lock.lock();
        if(runPlanner_ &&
           (ros::Time::now() > attempt_end || ++planning_retries_ > uint32_t(max_planning_retries_))){
          //we'll move into our obstacle clearing mode
          state_ = CLEARING;
          publishZeroVelocity();
          recovery_trigger_ = PLANNING_R;
        }
```

**Comment by AriYu** [comment]
@MoriKen254 
ありがとうございます :exclamation: 
確かに、`oscillation_timeout`と`max_planning_retries`を設定するとリカバリ動作に入りやすくなりました。

今日はリカバリ動作のチェックを行っていましたが、いくつか要望があります。
まず、旋回、直進の動作を現在は時間で制御していますが、ロボットドライバ側の仕様により時間だとタイミングにより毎回動作量が変わってしまいます。ですので、できれば移動量、回転量で制御できないでしょうか。

もう一つあるのですが、costmapを見ているはずですが、障害物があってもリカバリ動作を開始してしまうようです。また、動作の遷移毎にcostmapを見ることはできないでしょうか。つまり、後退する前にチェック、旋回する前にチェック、など。

あと、追加で開いてる方向に回転するだけのリカバリを作っていただくことは可能でしょうか？

以上、お忙しいところ申し訳ありませんが、検討していただけないでしょうか？

**Comment by MoriKen254** [comment]
@AriYu 
検証，要望をありがとうございます！
- [x] 移動量、回転量で制御
- [x] 動作の遷移毎にcostmapを見る
- [x] 追加で開いてる方向に回転するだけのリカバリを作る

承知しました．確かに，完成度が低かったですね^^;
検証して頂いて助かります．

改善版，早速着手します．

**Comment by MoriKen254** [comment]
TODO:
- [x] 旋回，移動開始前に障害物の有無を確認する．
- [x] 移動中のコストマップへのアクセス回数を減らす．

**Comment by MoriKen254** [comment]
TODO:
- [x] 各移動動作にタイムアウトを設ける。
- [x] 最短障害物検知時のコストマップへのアクセス頻度をもう少し改善する。

**Comment by AriYu** [comment]
実験を行ってみましたが、かなりいい感じに避けてくれるようになっています。
ありがとうございます。
たまに、

```
Map update loop missed its desired rate of 1.0000Hz... the loop actually  took xxxx seconds
```

というメッセージとともに後退できなくなってしまう問題は依然として生じてしまうことがあります。
この現象はロボット前方の非常に近い位置に障害物が突然現れるという場合によく起こるようです（実験的に）。
ですので、もしかすると`costmap`側のバグの可能性もあります。

**Comment by MoriKen254** [comment]
なるほど．障害物が突然発生した時に更新に時間がかかってしまう仕様かもしれませんね．

少し調べましたが，やはりワーニングを確実になくすためには，costmapの更新周期を遅くすればよさげです．
`local_costmap_params.yaml` の`update_frequency`を調節することになるかと．

ただ，特異な状態だけで発生するワーニングですし，タイムアウトも設けてあるので，現状致命的では無いとは思います．

もし現場で問題になったら，costmapあるいはrecoveryのパラメータを適宜調整してもらう，というスタンスで良いと思います．

一旦閉じますが，問題が起きたらまた開けて下さい．

以下，参考．
- フォーラム
  - [Slow observation buffer update warnings in move_base](http://answers.ros.org/question/11451/slow-observation-buffer-update-warnings-in-move_base/)
- コード: costmap_2d_ros.cpp 411行目
  - [ros-planning/navigation/blob/indigo-devel/costmap_2d/src/costmap_2d_ros.cpp](https://github.com/ros-planning/navigation/blob/indigo-devel/costmap_2d/src/costmap_2d_ros.cpp)
