### ISSUE TITLE
local_plannerについて

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/third_robot_pkg#13]
`move_base`の標準のローカルプランナーがディファレンシャルロボットを想定していることもあり、その場旋回の指令を送ってきたり、バックの指令は送ってこないという問題があります。
これは現在、指令値を受け取る`third_robot_driver`で小手先対応をしています。
なので時間があればローカルプランナーを自分で作りたいと思っていましたが、なかなか出来ませんでした。
ところで、たまたま以下のようなプランナを見つけました。
http://wiki.ros.org/teb_local_planner
ベータ機能みたいですが、car-likeなロボットもサポートしているみたいなので、時間があれば試してみたいと思います。

**Comment by MoriKen254** [comment]
@AriYu 
有益な情報をありがとうございます．
試してみましたが，良い感触です（またHuskeyですが…）．その場旋回ではなく，バックして旋回する挙動は素敵です．
https://www.youtube.com/watch?v=MQ-vwTP5wbs&edit=vd

3号機に対応した `min_turning_radius`の設定をすれば，無理のないプランを立ててくれそうですね．

3号機のGazeboでのナビ環境を整えるとき，これを使えるようにします．
　※中々時間が取れておらず，すみません…．

それと，https://github.com/rst-tu-dortmund/teb_local_planner のパッケージはどのリポジトリで管理しますか？
`CIR-KIT/TC2016_for_thirdrobot` パッケージで，wstoolによる管理を行いますか？

**Comment by AriYu** [comment]
@MoriKen254 
そうですね、とりあえず使ってみるという意味でも`CIR-KIT/TC2016_for_thirdrobot`で`wstool`で管理したいと思います。
後ほど追加します。

**Comment by AriYu** [comment]
少し試してみましたが計算量が多いですね。
あとなぜかスムーズに進まない問題があります。
あとこれは`third_robot_driver`の問題ですが、バックで上手く切り返せません…
でもなんとかこれを使って見たいので頑張ってみます。

**Comment by MoriKen254** [comment]
検証ありがとうございます。
パッとしか見ていませんし確証も無いのですが、ROS wikiで記載された仕様に最適化に関するパラメータがあるようです。余分な機能をカットして計算量を軽減できないかと思っています。私も後ほどもう少し読んでみます。

ドライバーも含め、頑張って下さい。

**Comment by MoriKen254** [comment]
下記ページ「Computation time」の節に計算時間に関わるパラメータの一覧が載っています．
[teb_local_plannerTutorialsFrequently Asked Questions](http://wiki.ros.org/teb_local_planner/Tutorials/Frequently%20Asked%20Questions)

やはり最適化パラメータの調整が鍵のようです．取り急ぎ共有です．

**Comment by AriYu** [comment]
@MoriKen254 
ありがとうございます。
もう少しパラメータ等を調整しながら実験してみたいと思います。

**Comment by AriYu** [comment]
今日一日実験してみましたが、採用するには時間がたりなさそうですので諦めます。
@MoriKen254 さんのリカバリ動作を導入したことで復帰できる可能性が大きく上がったのでなんとかもとのプランナで頑張りたいと思います。
調整パラメータが多すぎてちょっと時間が足りません…

**Comment by MoriKen254** [comment]
`teb_local_planner` の注意点．
- 早く動かす代償として，costmapの分解能を0.2程度にする必要がある．
  - LRFがロボット自身に当たる領域はfootprintの設定で無視しているが，分解能を大きくするとたまにコストマップとして認識されてしまう．
- 周囲に障害物が多くなると計算時間の増大が避けられない．パラメータで調整できるレベルではない．
- 回転頻度が半端無いので，オドメトリのキャリブレーションをしっかりしないといけない．
- ~~停止してもRecoveryに入らない．~~ → 無理やり妨害すればちゃんとリカバリする．tebの探索が優秀過ぎてスタックしないだけ．
