### ISSUE TITLE
Gazebo用PointCloudプラグイン使用時の座標のずれの問題

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#14]
ブランチ`add_pointcloud_gazebo`についてです．

3DセンサをGazebo上で模擬するために，`libgazebo_ros_openni_kinect.so`を使おうとしています．
該当コミットは[こちら](https://github.com/CIR-KIT/third_robot_pkg/commit/aac64ce0c8bb4e3e073a7cfff2bc4e5a096e96a8)

この状態でRvizで確認すると，下図のようになります．

![screenshot from 2016-10-17 00 02 27](https://cloud.githubusercontent.com/assets/12078261/19418348/06082ac6-93fd-11e6-894b-4a4474e36179.png)

参考にGazeboも．
![screenshot from 2016-10-17 00 04 16](https://cloud.githubusercontent.com/assets/12078261/19418360/490daac6-93fd-11e6-8659-f6a6d29a80d3.png)

Rviz上の黄色表示領域がPointCloudのデータです．データ自体は前方のデータをとれているようです（前方に位置する，立方体の平面と円柱の鏡面を捉えた点群であることが分かる）．

ところが，表示の向きがおかしいです．本来前方を向いて欲しいのに，下方向，さらに90度回転したものになっています．この点群データをちゃんと前方に表示させたいです．

モデルの構成が悪いとは思うのですが，ちょっといじってみてもよく分かりませんでした…．

どなたか（特にKinect使いのMotomanグループの方），助言をいただけますか？

**Comment by AriYu** [comment]
@MoriKen254 
まず、申し上げてなかったですが、3Dlidarは逆さまに取り付けてあります。
ですので、tfも180度回転させてあります。
もしかするとそれが原因かもしれません。

**Comment by RyodoTanaka** [comment]
@MoriKen254 @AriYu 
返事遅くなってすみません。

Kinectの位置ずれですが、これは仕様によるものです。
Kinectのフレームはデフォルトでz軸方向に向かって出るようになっています。
おそらく、カメラモデルのためだと思うのですが、詳しくは知りません。
どなたか知っていたら教えていただけると嬉しいです。
いずれにせよ、上記の理由で今回の位置ずれが起きます。

対策方法としては、新たに回転させたフレームを追加し、その座標系にKinectを置く以外ありません。
通常、`hoge_hoge_optical_flame`という名前で回転させた座標系が追加されていることが多いです。

Motomanで使用しているものも、`kinect_rgb_flame`から回転させた`kinect_rgb_optical_flame`なるものを設定しています。

実機との祖語が生じてしまいますが、TFを登録するだけなので問題は起きないのではないかと思います。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
それから、今回は点群しか使わないので必要ありませんが、KinectのGazeboモデルはRGBの順番がBGRになっているので、`<format>B8G8R8</format>`と記述しないと色が変になっちゃうっていうのもあります。
完全に蛇足ですが、備忘録もかねて...

**Comment by MoriKen254** [comment]
@AriYu @RyodoTanaka 
さっそくありがとう！

なるほど、プラグインの仕様、理解しました。
z軸が前方なのは、おっしゃる通りの理由に思われますね。

また、実はカメラの画像も逆さまだったり、色が反転した感じになっていたのが気になっていたので、全部助言が関係していそうです。とても助かります。

1つずつ解決してみます。また連絡します。

**Comment by MoriKen254** [comment]
無事に向きが直りました（逆さについている件，TFフレームを追加する件）．
迅速な対応をいただき，ありがとうございます．とても助かりました．

![screenshot from 2016-10-17 09 07 35](https://cloud.githubusercontent.com/assets/12078261/19422058/5bb7ceda-9449-11e6-961d-1518cb321ec0.png)

**Comment by MoriKen254** [comment]
あー！すみません。LIDERを逆さに付けていたのは意図的なのですね。
今のリクエストでは向きを元に戻してしまっています…。

逆さにした状態でうまく動くか確認しまふ。

**Comment by MoriKen254** [comment]
度々申し訳ございません．LIDERを上下逆さにしても使えました（画像も逆さ，TFも逆さになっています）．

お騒がせ致しました．

![screenshot from 2016-10-17 12 31 58](https://cloud.githubusercontent.com/assets/12078261/19424700/4811a1b8-9466-11e6-888c-a0a27fc00660.png)

**Comment by AriYu** [comment]
@MoriKen254 

> LIDERを逆さに付けていたのは意図的なのですね。

はい、その通りです。
YVTX002は上の視野角が広く下が狭いため、そのまま取り付けるとかなり先まで地面のあたりの点群が取れなくなってしまいます。
