### ISSUE TITLE
Local Plannerについて

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/third_robot_pkg#20]
よくよく見てみるとDWAプランナーが使えてなくて、`TrajectryPlannerROS`を使っていました。
思い込みでした。
`DWA`プランナーはちゃんと避けますね…

**Comment by MoriKen254** [comment]
@AriYu 
`<param name="base_local_planner" value="dwa_local_planner/DWAPlannerROS" />` のところですよね．

dwaを有効にするフラグ的なパラメータは罠だったのですかね ^^;

何にせよ，良いプランナーが使えるようになってよかったです．
