### ISSUE TITLE
rviz上にhokuyo3Dのモデルが出ない

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT/third_robot_pkg#3]
tfはちゃんと発行されてるんですが、モデルがrviz上に出てきません。
他のモデル等はちゃんと表示されており、またエラー等も出ず…
何か解決策が分かれば教えてください。

**Comment by MoriKen254** [comment]
@AriYu 
原因が見えませんが，とりあず思いついた点を．

## センサが本体に埋め込まれている可能性
- 中心座標をわざとずらしてみてみる．もし表に出てくれば，本体に埋め込まれてしまっただけかも．

## センサの中心座標がずれている
- もし上記が起こる場合，以前の使っていたLRFと中心座標がずれているかもしれませんが，いかがでしょう．

## gazebo動作時のrviz上でのセンサ値
- ちなみに，gazeboで動かした時，rviz上でhokuyo3Dのセンサ情報は表示できますか？向きが異なったり，本体と干渉したりして変な値が出たりしていませんか？

今思いついたのはこんなところです．

**Comment by MoriKen254** [comment]
追伸

もし、ロボットモデル上で3Dセンサがどうしても表示されない場合、以下の確認をすればもう少し問題の切り分けができるかも。

3Dセンサのモデルだけリンクを持つURDFモデルを作って、/robot_descriptionに登録する。これなら他に干渉するものがありませんし、一応colladaモデルにおける物体座標系の向きを確認できます。

もしこれでも3Dセンサが表示されないなら、3Dセンサモデル単体で問題が閉じます。

これで3Dセンサが表示されるなら、ロボットのURDFモデル側の構成の問題になると推察されます。

**Comment by AriYu** [comment]
@MoriKen254 
コメントありがとうございます。
昨年作ったということもあって`xacro`は使ってなくて直接URDFを使っています。
tfの座標変換は上手く動いているようなので、モデルがずれているというのは考えづらいと思っています。
また、gazebo上ではちゃんと正しい位置に表示されています。ただgazeboは`xacro`を使っています。

座標変換はちゃんとできていることもあり、あまり重要ではないので、時間があればもう少し調べます。

**Comment by AriYu** [comment]
@MoriKen254 
ご指摘通り、モデルの位置がずれていました。
ただ、gazeboとrviz上で表示される位置が異なっているのかはまだ分かっていません。

**Comment by MoriKen254** [comment]
@AriYu 
こちらでmasterブランチにして確認したら，gazeboでもrvizでも表示されています．
※私が確認したのはxacroの方ですが．
もしかして，もう手を打ちましたか？一応，確認です．

![screenshot from 2016-10-12 18 58 59](https://cloud.githubusercontent.com/assets/12078261/19305922/2f1aede2-90ae-11e6-94e4-678583d48df0.png)

![screenshot from 2016-10-12 18 59 24](https://cloud.githubusercontent.com/assets/12078261/19305926/33e4550c-90ae-11e6-9b3b-f07bf10d9082.png)

**Comment by AriYu** [comment]
@MoriKen254 
確認ありがとうございます。
gazeboでは以前から正しく表示されており、通常起動の場合にurdfを直接呼び出している時に上手く行っていませんでした。
通常起動の際にもxacroから起動するように Pull #8 で変更しました。
