### ISSUE TITLE
遠隔モニタリング

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#31]
※30日最終実験日まで返信不要です．

30日に，昨年やりそびれた遠隔監視の確認もしたいです．私メインでOKです．

ベースは残っているので，改良します．
https://github.com/CIR-KIT/third_robot_pkg/tree/master/third_robot_monitor

最悪，30日に `rosbag` を貰えればなんとかなる…？と思います．

**Comment by AriYu** [comment]
@moriken254
分かりました。
何か必要なものがあれば教えて下さい。出来るだけ協力したいと思います。
よろしくお願いします。

2016年10月27日木曜日、Masaru Moritanotifications@github.comさんは書きました:

**Comment by MoriKen254** [comment]
#32 でマージしました．実機での検証＋要望仕様追加後に閉じましょう．

Gazeboの検証環境，快適です♪
