### ISSUE TITLE
やり残した細かいこと

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#43]
`third_robot_pkg`でやり残して気になっている細かいことを書いておきます。Advent Calender 投稿までに改善予定。

##  全体
- [ ] ドキュメントを充実させる。
  - topic、param 一覧など
- [ ] ライセンス関係。お作法とか。
- [ ] 命名規約等を統一する。
- [ ] travisを通したい。
- [ ] 不使用のpkgをarchiveする。

## description
- [ ] フォルダ構成を見直す。
- [ ] テクスチャを付ける。

## SteerBot
- [ ] 指令値に係数をかける処理をハードコーディングしている。パラメータで調整できるようにする。
- [ ] インタフェース登録処理の部分をオブジェクト指向化する。
- [ ] KineticKameで動くかを確認する。（MultiInterfaceControllerは本来はIndigoでは使えない）

## SteerDrivecontroller
- [ ] limitterをちゃんと使う。
- [ ] testコードを通す。

**Comment by forno** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/20
にて閉じることが決定。

最新の仕事は同リポジトリのIssueを参照してください。
