### ISSUE TITLE
SetVelocityが使えない問題について

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/third_robot_pkg#5]
@MoriKen254 
私も以前、Velodyneのプラグインをつくろうとした際に、SetVelocity関数がなくて悩みました。
調べたところ、Indigo(正確には、Gazebo 4.0 未満)には、SetVelocity関数が定義されていないためです。

その代わり、physics::LinkPtrのメソッドに
SetLinearVel
SetAngularVel
というのがあり、これを利用したところ、うまく行きました。
すぐにやってみますが、少し時間をください。ちなみに、実装した時のソースは以下にあります。
https://github.com/RyodoTanaka/velodyne_gazebo/blob/add-pointcloud/velodyne_gazebo_plugin/src/velodyne_plugin.cpp
上記のソースだと、linkの設定の仕方を番号で指定しているのでわかりづらいかも知れません...
以上、よろしくお願いします。

**Comment by MoriKen254** [comment]
@RyodoTanaka 
ありがとう．じっくり見れていないのですが，そんないい方法があったのですね．

実はその後，VELOCITY_PIDでいい感じに動くようになり，とりあえずこれで行こうと思います．
※[DefaultRobotHWSim](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp) と同じ実装です．

直接Velを指定できるのは便利なので，参考にさせてもらいます．ありがとう．
