### ISSUE TITLE
オープン化時の3号機の名前

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#50]
@AriYu @RyodoTanaka 

Organizationを英語名にしたいのですが，いくつか案があります．皆さんの意見を下さい．

案に寄ってはパッケージ名の変更が必要となりますが，この際書きなおして依存関係等を排除するきっかけにするのはどうでしょう．

- CIR-KIT_third_robot
  - パッケージ名を従来通りにできるので移植が楽．
  - もう少し装飾感があってもいいかな？とも思う．

- CIR-KIT_Unit-03
  - エヴァやガンダムでは「○号機」をUnit○と呼ぶらしい．
  - パッケージ名を修正する必要あり．

- KIT-C3
  - つくちゃ登録名．ロボット名って感じがして，悪くないと思う．
  - Cの由来はなんでしょうか？
  - パッケージ名を修正する必要あり．

**Comment by AriYu** [comment]
ROSのパッケージ名はアンダースコアでつなぐというルールがありますが、CIR-KITとした場合に問題にならないでしょうか？

KIT-C3のCの由来は分かりかねます。というのもわたしが参加した時点で既に使われており、由来もその時点であやふやでした。もしかしたらCIR-KITのCかもしれません。（余談ですがCIR-KITはCreate
Intellectual Robot Kyushu Institute of Technolgyの略らしいということを聞いた記憶があります。）

2016年11月6日日曜日、Masaru Moritanotifications@github.comさんは書きました:

**Comment by shimoe** [comment]
"詳説　ROSロボットプログラミング"によると，命名則としてROSのパッケージ名は小文字かつアンダースコアで結ぶとあるのでCIR-KITは入れるならcir_kitないしcirkitにした方がいいと思います．
思いつく案としては

・cirkit_unit_3rd
・3rd_cirkit_unit
・cirkit_3rd_robot

などでしょうか．個人的には機体番号が最初に来たほうが良いと思います．(3rd_cirkit_unitなど)

**Comment by MoriKen254** [comment]
早速のご意見，本当にありがとうございます！非常に参考になります．

## Organization

まず，Organization名は大文字やハイフンを用いてもよいので，([Husky](https://github.com/husky)の例あり)，こちらは見た目を最優先で，
- CIR-KIT_Unit-3

でも良いかな？と思いましたが，如何でしょうか．

## Package

### 命名規則

皆さんのご意見の通り，小文字＋アンダースコアで行きましょう．

### 号機の表現

また，英語でロボット等の「号機」を表現する場合，
- 「序数詞+unit (例：3rd unit)」

という用法もあるようですが，
- 「unit+基数詞 (例：unit 03)」

という用法が一般的のようです．

Google検索をすると，3rd unit→約15万件，unit 03→約44万件なので，unit+基数詞で行こうと思います^^
参考に，3rd robotは約8000件となりました．

### パッケージに利用するロボット名

諸々考慮して，パッケージ側でロボット名を使用する部分は
- cirkit_unit3

とするのは如何でしょうか？

> 個人的には機体番号が最初に来たほうが良いと思います．(3rd_cirkit_unitなど)

というご意見を頂いたので，数字を最後にするのは心苦しいのですが，エヴァやガンダムを見ると
- Evangelion Unit 03
- RX-78-4 Gundam Unit 4

となっており，数字を最後に来るのがしっくり来そうです．数字が先頭のほうが補間等が楽というメリットはあるのは重々分かるのですが，ここは英語名の整合性に重きを置きたいと思います．

一旦作ってみるかもしれませんが，後で変更可能なので，もしまたご意見あればよろしくお願いします．

### CIR-KITの由来

ありがとうございます．なるほど，かっこいいですね！

**Comment by AriYu** [comment]
@MoriKen254 
Organization名ですが、なんとなくですが、
CIR-KIT_Unit-3 -> CIR-KIT_Unit03, CIR-KIT_Unit-03
がいいかなぁと思います。無いとは思いますが、ロボットの台数が２桁を超えることがあるかもしれません。
しかし、アンダースコアとハイフンが併用されるのはなんか違和感があります…
パッケージ名も同様に0を加えていただき、
cirkit_unit03
が個人的にはいいかなと思います。

**Comment by MoriKen254** [comment]
@AriYu 
コメントありがとう！

> アンダースコアとハイフンが併用されるのはなんか違和感があります…

そうですね．では，こうしましょう．

## Organization名

`CIR-KIT`の正式名称でハイフンを利用していることを尊重し，
- CIR-KIT-Unit03

とします．`CIR_KIT_Unit03`と書き出してみたら，`CIR_KIT`の部分に違和感がある気がしました^^;

## Package名内の名称
- cirkit_unit03_hogehoge

## 具体的なPackage名一覧

3号機に特化する部分と，3号機非依存の部分に分けて，以下のような構成にしようと思います．
cirkit_unit03 に.rosinstallを配置して，必要なリポジトリを引っ張ってくる構成を想定しています．

![package_config](https://cloud.githubusercontent.com/assets/12078261/20058699/9a8c7802-a535-11e6-890d-470917fc76d7.png)

**Comment by AriYu** [comment]
@MoriKen254 
ちなみに、今あるプログラムのコミットを引き継ぎますか？
それともfirst commitから始めますか？
個人的にはコミットを引き継いだほうがいいかなーと思っています。
コミットが汚い部分もあるとは思いますが…

**Comment by MoriKen254** [comment]
@AriYu 
そうですね、念のため引き継ぎましょう。
まぁ多少汚くても気にしないことにしましょう笑。

**Comment by MoriKen254** [comment]
@AriYu @shimoe 
ご協力ありがとうございました。
ひとまずこれで進めます。
