### ISSUE TITLE
SteerDriveController とりあえず動きます．

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#6]
@AriYu @RyodoTanaka 
[以前立てたissue](https://github.com/Nishida-Lab/TC2015/issues/64)の構成で最低限動くSteerDriveControllerとSteerBotが出来ました．

左右前輪に仮想のステアjointを付けて，RobotHWSim側で構成の違い（gazeboで閉リンクが使えない）を吸収しています．これなら実機と共通でSteerDriveControllerが使えると思います．

相談に乗っていただき，ありがとうございました．

![screenshot from 2016-10-08 01 29 30](https://cloud.githubusercontent.com/assets/12078261/19197795/cfd1aef8-8cf6-11e6-90c7-67d5998ce85f.png)

まだ突貫工事なので，引き続き完成度を上げつつ，Gazebo上でナビゲーションのリカバリ行動検証まで実施する計画です．ある程度育ったらプルリク投げます．

人物検出の優先度が高いですが，もし実機のコントローラをros_control化する予定があれば，現状でも互換性の確認くらいには使えると思います．※オドメトリは未実装です．

詳細は[Wikiページ](https://github.com/CIR-KIT/third_robot_pkg/wiki/SteerDriveController-%E3%82%92-gazebo%E4%B8%8A%E3%81%AE-SteerBot-%E3%81%A7%E5%8B%95%E3%81%8B%E3%81%99)を参照下さい．

もし気が向いて触ってみたとき，手順通りにコマンドを打っても動かない場合，教えて下さい．

**Comment by MoriKen254** [comment]
@AriYu 
オドメトリもステアリング型に更新したものができました．

![screenshot from 2016-10-10 08 14 06](https://cloud.githubusercontent.com/assets/12078261/19224465/9521e120-8ec1-11e6-928d-2a93546b4b17.png)

このまま既存LRFでRotateRecoveryに入ろうかと思いましたが，その前にちょっと確認です．

先にプルリク出して3Dセンサ版と統合させてからのほうが良いかなとも思いました．

そちらの作業と干渉しない形ですすめたいので，意見もらえますか？

**Comment by AriYu** [comment]
@MoriKen254 
素晴らしいです。
本当は実機も`ros_control`に対応させたいのですが、なかなか時間が取れそうにありません。

そうですね、先にプルリクを頂いてマージしてからのほうが、いいかもしれません。
よろしくお願いします。

**Comment by MoriKen254** [comment]
@AriYu 
そうですね，人物検出に集中したほうがいいですね．
`ros_control`はgazeboでの回避行動の検証で使います．

プルリクの件，了解です．もう少し整理したら出しますね．よろしく．

**Comment by MoriKen254** [comment]
TODO:
- [x] アッカーマンリンク機構に対応させる。
- [ ] ~~汎用性を持たせるため前輪2つのホイールのTFは廃止する。~~
